[2022-12-25T16:17:05.881+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ETL_toll_data.test_impersonated_user manual__2022-12-25T16:17:03.026150+00:00 [queued]>
[2022-12-25T16:17:05.901+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ETL_toll_data.test_impersonated_user manual__2022-12-25T16:17:03.026150+00:00 [queued]>
[2022-12-25T16:17:05.902+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T16:17:05.902+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2022-12-25T16:17:05.902+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T16:17:05.948+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): test_impersonated_user> on 2022-12-25 16:17:03.026150+00:00
[2022-12-25T16:17:05.949+0000] {base_task_runner.py:129} INFO - Running on host: 8fd7e45d4638
[2022-12-25T16:17:05.949+0000] {base_task_runner.py:130} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'test_impersonated_user', 'manual__2022-12-25T16:17:03.026150+00:00', '--job-id', '271', '--raw', '--subdir', 'DAGS_FOLDER/toll_data_etl.py', '--cfg-path', '/tmp/tmpqx7b2v5i']
[2022-12-25T16:17:09.016+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user /home/***/.local/lib/python3.7/site-packages/***/plugins_manager.py:258 RemovedInAirflow3Warning: This decorator is deprecated.
[2022-12-25T16:17:09.016+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user 
[2022-12-25T16:17:09.017+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user In previous versions, all subclasses of BaseOperator must use apply_default decorator for the `default_args` feature to work properly.
[2022-12-25T16:17:09.017+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user 
[2022-12-25T16:17:09.017+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user In current version, it is optional. The decorator is applied automatically using the metaclass.
[2022-12-25T16:17:09.017+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user 
[2022-12-25T16:17:09.437+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user [[34m2022-12-25 16:17:09,437[0m] {[34mdagbag.py:[0m538} INFO[0m - Filling up the DagBag from /opt/***/dags/toll_data_etl.py[0m
[2022-12-25T16:17:10.650+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user [[34m2022-12-25 16:17:10,649[0m] {[34mtask_command.py:[0m389} INFO[0m - Running <TaskInstance: ETL_toll_data.test_impersonated_user manual__2022-12-25T16:17:03.026150+00:00 [running]> on host 8fd7e45d4638[0m
[2022-12-25T16:17:11.066+0000] {local_task_job.py:207} WARNING - Recorded pid 865 does not match the current pid 866
[2022-12-25T16:17:11.069+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 866. PIDs of all processes in the group: [866]
[2022-12-25T16:17:11.069+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 866
[2022-12-25T16:17:11.069+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-12-25T16:17:11.070+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2022-12-25T16:17:11.100+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1378, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1500, in _execute_task_with_callbacks
    RenderedTaskInstanceFields.write(rtif)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/renderedtifields.py", line 183, in write
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3057, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3135, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2856, in get
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2974, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 335, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1570, in _execute_clauseelement
    linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 538, in _compile_w_cache
    **kw
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 567, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 804, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 463, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 498, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3318, in visit_select
    select_stmt, self, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 510, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/context.py", line 765, in create_for_statement
    self._setup_for_generate()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/context.py", line 875, in _setup_for_generate
    entity.setup_compile_state(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/context.py", line 2670, in setup_compile_state
    polymorphic_discriminator=self._polymorphic_discriminator,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 621, in _setup_entity_query
    **kw
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 647, in setup
    context, query_entity, path, loader, adapter, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 2039, in setup_query
    chained_from_outerjoin=chained_from_outerjoin,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 621, in _setup_entity_query
    **kw
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 647, in setup
    context, query_entity, path, loader, adapter, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 208, in setup_query
    c = adapter.columns[c]
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 985, in __getitem__
    return self.columns[key]
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 762, in __missing__
    self[key] = val = self.creator(self.weakself(), key)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 1024, in _locate_col
    c = vis.replace(col, _include_singleton_constants=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 908, in replace
    return self._corresponding_column(col, True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 834, in _corresponding_column
    col, require_embedded=require_embedded
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 227, in corresponding_column
    column, require_embedded
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 1399, in corresponding_column
    expanded_proxy_set = set(_expand_cloned(c.proxy_set))
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 157, in _expand_cloned
    return itertools.chain(*[x._cloned_set for x in elements])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 157, in <listcomp>
    return itertools.chain(*[x._cloned_set for x in elements])
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-12-25T16:17:11.203+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_toll_data, task_id=test_impersonated_user, execution_date=20221225T161703, start_date=20221225T161705, end_date=20221225T161711
[2022-12-25T16:17:11.285+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:120 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2022-12-25T16:17:11.285+0000] {configuration.py:635} WARNING - section/key [smtp/smtp_user] not found in config
[2022-12-25T16:17:11.286+0000] {email.py:229} INFO - Email alerting: attempt 1
[2022-12-25T16:17:11.301+0000] {configuration.py:635} WARNING - section/key [smtp/smtp_user] not found in config
[2022-12-25T16:17:11.302+0000] {email.py:229} INFO - Email alerting: attempt 1
[2022-12-25T16:17:11.303+0000] {taskinstance.py:1835} ERROR - Failed to send email to: ['bala@yopmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1378, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1500, in _execute_task_with_callbacks
    RenderedTaskInstanceFields.write(rtif)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/renderedtifields.py", line 183, in write
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3057, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3135, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2856, in get
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2974, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 335, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1570, in _execute_clauseelement
    linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 538, in _compile_w_cache
    **kw
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 567, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 804, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 463, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 498, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3318, in visit_select
    select_stmt, self, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 510, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/context.py", line 765, in create_for_statement
    self._setup_for_generate()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/context.py", line 875, in _setup_for_generate
    entity.setup_compile_state(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/context.py", line 2670, in setup_compile_state
    polymorphic_discriminator=self._polymorphic_discriminator,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 621, in _setup_entity_query
    **kw
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 647, in setup
    context, query_entity, path, loader, adapter, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 2039, in setup_query
    chained_from_outerjoin=chained_from_outerjoin,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 621, in _setup_entity_query
    **kw
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 647, in setup
    context, query_entity, path, loader, adapter, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 208, in setup_query
    c = adapter.columns[c]
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 985, in __getitem__
    return self.columns[key]
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 762, in __missing__
    self[key] = val = self.creator(self.weakself(), key)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 1024, in _locate_col
    c = vis.replace(col, _include_singleton_constants=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 908, in replace
    return self._corresponding_column(col, True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 834, in _corresponding_column
    col, require_embedded=require_embedded
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 227, in corresponding_column
    column, require_embedded
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 1399, in corresponding_column
    expanded_proxy_set = set(_expand_cloned(c.proxy_set))
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 157, in _expand_cloned
    return itertools.chain(*[x._cloned_set for x in elements])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 157, in <listcomp>
    return itertools.chain(*[x._cloned_set for x in elements])
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2235, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1833, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2237, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2022-12-25T16:17:11.413+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user Traceback (most recent call last):
[2022-12-25T16:17:11.413+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/bin/***", line 8, in <module>
[2022-12-25T16:17:11.414+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     sys.exit(main())
[2022-12-25T16:17:11.414+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/***/__main__.py", line 39, in main
[2022-12-25T16:17:11.414+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     args.func(args)
[2022-12-25T16:17:11.414+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 52, in command
[2022-12-25T16:17:11.415+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     return func(*args, **kwargs)
[2022-12-25T16:17:11.415+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 108, in wrapper
[2022-12-25T16:17:11.415+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     return f(*args, **kwargs)
[2022-12-25T16:17:11.415+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 396, in task_run
[2022-12-25T16:17:11.416+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     _run_task_by_selected_method(args, dag, ti)
[2022-12-25T16:17:11.416+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 195, in _run_task_by_selected_method
[2022-12-25T16:17:11.416+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     _run_raw_task(args, ti)
[2022-12-25T16:17:11.416+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 272, in _run_raw_task
[2022-12-25T16:17:11.417+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     pool=args.pool,
[2022-12-25T16:17:11.417+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/***/utils/session.py", line 75, in wrapper
[2022-12-25T16:17:11.417+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     return func(*args, session=session, **kwargs)
[2022-12-25T16:17:11.417+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1378, in _run_raw_task
[2022-12-25T16:17:11.418+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     self._execute_task_with_callbacks(context, test_mode)
[2022-12-25T16:17:11.418+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1500, in _execute_task_with_callbacks
[2022-12-25T16:17:11.418+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     RenderedTaskInstanceFields.write(rtif)
[2022-12-25T16:17:11.418+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/***/utils/session.py", line 75, in wrapper
[2022-12-25T16:17:11.419+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     return func(*args, session=session, **kwargs)
[2022-12-25T16:17:11.419+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py", line 183, in write
[2022-12-25T16:17:11.419+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     session.merge(self)
[2022-12-25T16:17:11.420+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3057, in merge
[2022-12-25T16:17:11.420+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     _resolve_conflict_map=_resolve_conflict_map,
[2022-12-25T16:17:11.420+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3135, in _merge
[2022-12-25T16:17:11.420+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     options=options,
[2022-12-25T16:17:11.421+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2856, in get
[2022-12-25T16:17:11.421+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     execution_options=execution_options,
[2022-12-25T16:17:11.421+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2974, in _get_impl
[2022-12-25T16:17:11.421+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     load_options=load_options,
[2022-12-25T16:17:11.422+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
[2022-12-25T16:17:11.422+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     bind_arguments=bind_arguments,
[2022-12-25T16:17:11.422+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
[2022-12-25T16:17:11.422+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     result = conn._execute_20(statement, params or {}, execution_options)
[2022-12-25T16:17:11.423+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
[2022-12-25T16:17:11.423+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     return meth(self, args_10style, kwargs_10style, execution_options)
[2022-12-25T16:17:11.423+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 335, in _execute_on_connection
[2022-12-25T16:17:11.424+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     self, multiparams, params, execution_options
[2022-12-25T16:17:11.424+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1570, in _execute_clauseelement
[2022-12-25T16:17:11.425+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
[2022-12-25T16:17:11.425+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 538, in _compile_w_cache
[2022-12-25T16:17:11.425+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     **kw
[2022-12-25T16:17:11.426+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 567, in _compiler
[2022-12-25T16:17:11.426+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     return dialect.statement_compiler(dialect, self, **kw)
[2022-12-25T16:17:11.427+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 804, in __init__
[2022-12-25T16:17:11.427+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     Compiled.__init__(self, dialect, statement, **kwargs)
[2022-12-25T16:17:11.428+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 463, in __init__
[2022-12-25T16:17:11.428+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     self.string = self.process(self.statement, **compile_kwargs)
[2022-12-25T16:17:11.428+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 498, in process
[2022-12-25T16:17:11.428+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     return obj._compiler_dispatch(self, **kwargs)
[2022-12-25T16:17:11.429+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
[2022-12-25T16:17:11.429+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     return meth(self, **kw)
[2022-12-25T16:17:11.429+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3318, in visit_select
[2022-12-25T16:17:11.429+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     select_stmt, self, **kwargs
[2022-12-25T16:17:11.430+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 510, in create_for_statement
[2022-12-25T16:17:11.430+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     return klass.create_for_statement(statement, compiler, **kw)
[2022-12-25T16:17:11.430+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/orm/context.py", line 765, in create_for_statement
[2022-12-25T16:17:11.430+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     self._setup_for_generate()
[2022-12-25T16:17:11.430+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/orm/context.py", line 875, in _setup_for_generate
[2022-12-25T16:17:11.431+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     entity.setup_compile_state(self)
[2022-12-25T16:17:11.431+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/orm/context.py", line 2670, in setup_compile_state
[2022-12-25T16:17:11.431+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     polymorphic_discriminator=self._polymorphic_discriminator,
[2022-12-25T16:17:11.431+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 621, in _setup_entity_query
[2022-12-25T16:17:11.431+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     **kw
[2022-12-25T16:17:11.432+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 647, in setup
[2022-12-25T16:17:11.432+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     context, query_entity, path, loader, adapter, **kwargs
[2022-12-25T16:17:11.432+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 2039, in setup_query
[2022-12-25T16:17:11.432+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     chained_from_outerjoin=chained_from_outerjoin,
[2022-12-25T16:17:11.433+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 621, in _setup_entity_query
[2022-12-25T16:17:11.433+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     **kw
[2022-12-25T16:17:11.433+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 647, in setup
[2022-12-25T16:17:11.433+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     context, query_entity, path, loader, adapter, **kwargs
[2022-12-25T16:17:11.433+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 208, in setup_query
[2022-12-25T16:17:11.434+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     c = adapter.columns[c]
[2022-12-25T16:17:11.434+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 985, in __getitem__
[2022-12-25T16:17:11.434+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     return self.columns[key]
[2022-12-25T16:17:11.434+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 762, in __missing__
[2022-12-25T16:17:11.434+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     self[key] = val = self.creator(self.weakself(), key)
[2022-12-25T16:17:11.435+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 1024, in _locate_col
[2022-12-25T16:17:11.435+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     c = vis.replace(col, _include_singleton_constants=True)
[2022-12-25T16:17:11.435+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 908, in replace
[2022-12-25T16:17:11.435+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     return self._corresponding_column(col, True)
[2022-12-25T16:17:11.435+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 834, in _corresponding_column
[2022-12-25T16:17:11.436+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     col, require_embedded=require_embedded
[2022-12-25T16:17:11.436+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 227, in corresponding_column
[2022-12-25T16:17:11.436+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     column, require_embedded
[2022-12-25T16:17:11.436+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 1399, in corresponding_column
[2022-12-25T16:17:11.436+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     expanded_proxy_set = set(_expand_cloned(c.proxy_set))
[2022-12-25T16:17:11.437+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 157, in _expand_cloned
[2022-12-25T16:17:11.437+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     return itertools.chain(*[x._cloned_set for x in elements])
[2022-12-25T16:17:11.437+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 157, in <listcomp>
[2022-12-25T16:17:11.437+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     return itertools.chain(*[x._cloned_set for x in elements])
[2022-12-25T16:17:11.437+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1485, in signal_handler
[2022-12-25T16:17:11.438+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user     raise AirflowException("Task received SIGTERM signal")
[2022-12-25T16:17:11.438+0000] {base_task_runner.py:116} INFO - Job 271: Subtask test_impersonated_user ***.exceptions.AirflowException: Task received SIGTERM signal
[2022-12-25T16:17:11.804+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=866, status='terminated', exitcode=1, started='16:17:05') (866) terminated with exit code 1
