[2022-12-25T14:22:47.006+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ETL_toll_data.unzip_data manual__2022-12-25T14:21:28.752914+00:00 [queued]>
[2022-12-25T14:22:47.016+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ETL_toll_data.unzip_data manual__2022-12-25T14:21:28.752914+00:00 [queued]>
[2022-12-25T14:22:47.016+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T14:22:47.016+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 3
[2022-12-25T14:22:47.016+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T14:22:47.040+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): unzip_data> on 2022-12-25 14:21:28.752914+00:00
[2022-12-25T14:22:47.041+0000] {base_task_runner.py:129} INFO - Running on host: 8fd7e45d4638
[2022-12-25T14:22:47.042+0000] {base_task_runner.py:130} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'unzip_data', 'manual__2022-12-25T14:21:28.752914+00:00', '--job-id', '260', '--raw', '--subdir', 'DAGS_FOLDER/toll_data_etl.py', '--cfg-path', '/tmp/tmpuq8dmp_d']
[2022-12-25T14:22:48.539+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data /home/***/.local/lib/python3.7/site-packages/***/plugins_manager.py:258 RemovedInAirflow3Warning: This decorator is deprecated.
[2022-12-25T14:22:48.539+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data 
[2022-12-25T14:22:48.540+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data In previous versions, all subclasses of BaseOperator must use apply_default decorator for the `default_args` feature to work properly.
[2022-12-25T14:22:48.540+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data 
[2022-12-25T14:22:48.540+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data In current version, it is optional. The decorator is applied automatically using the metaclass.
[2022-12-25T14:22:48.540+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data 
[2022-12-25T14:22:48.720+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data [[34m2022-12-25 14:22:48,720[0m] {[34mdagbag.py:[0m538} INFO[0m - Filling up the DagBag from /opt/***/dags/toll_data_etl.py[0m
[2022-12-25T14:22:49.235+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data [[34m2022-12-25 14:22:49,234[0m] {[34mtask_command.py:[0m389} INFO[0m - Running <TaskInstance: ETL_toll_data.unzip_data manual__2022-12-25T14:21:28.752914+00:00 [running]> on host 8fd7e45d4638[0m
[2022-12-25T14:22:49.373+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=bala@yopmail.com
AIRFLOW_CTX_DAG_OWNER=bala
AIRFLOW_CTX_DAG_ID=ETL_toll_data
AIRFLOW_CTX_TASK_ID=unzip_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-25T14:21:28.752914+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-25T14:21:28.752914+00:00
[2022-12-25T14:22:49.374+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-25T14:22:49.374+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DB0250EN-SkillsNetwork/labs/Final%20Assignment/tolldata.tgz &&  tar zxvf tolldata.tgz -C ./data']
[2022-12-25T14:22:49.380+0000] {subprocess.py:86} INFO - Output:
[2022-12-25T14:22:49.389+0000] {subprocess.py:93} INFO - --2022-12-25 14:22:49--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DB0250EN-SkillsNetwork/labs/Final%20Assignment/tolldata.tgz
[2022-12-25T14:22:49.699+0000] {subprocess.py:93} INFO - Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 169.45.118.108
[2022-12-25T14:22:50.005+0000] {subprocess.py:93} INFO - Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.45.118.108|:443... connected.
[2022-12-25T14:22:50.972+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 200 OK
[2022-12-25T14:22:50.972+0000] {subprocess.py:93} INFO - Length: 528994 (517K) [application/x-tar]
[2022-12-25T14:22:50.973+0000] {subprocess.py:93} INFO - Saving to: â€˜tolldata.tgzâ€™
[2022-12-25T14:22:50.973+0000] {subprocess.py:93} INFO - 
[2022-12-25T14:22:51.461+0000] {subprocess.py:93} INFO -      0K .......... .......... .......... .......... ..........  9%  102K 5s
[2022-12-25T14:22:51.745+0000] {subprocess.py:93} INFO -     50K .......... .......... .......... .......... .......... 19%  176K 3s
[2022-12-25T14:22:51.748+0000] {subprocess.py:93} INFO -    100K .......... .......... .......... .......... .......... 29% 15.1M 2s
[2022-12-25T14:22:52.180+0000] {local_task_job.py:207} WARNING - Recorded pid 296 does not match the current pid 297
[2022-12-25T14:22:52.182+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 297. PIDs of all processes in the group: [308, 309, 310, 297]
[2022-12-25T14:22:52.182+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 297
[2022-12-25T14:22:52.183+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-12-25T14:22:52.183+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2022-12-25T14:22:52.186+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=309, status='terminated', started='14:22:49') (309) terminated with exit code None
[2022-12-25T14:22:52.187+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=310, status='terminated', started='14:22:49') (310) terminated with exit code None
[2022-12-25T14:22:52.196+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 191, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-12-25T14:22:52.200+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_toll_data, task_id=unzip_data, execution_date=20221225T142128, start_date=20221225T142247, end_date=20221225T142252
[2022-12-25T14:22:52.254+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:120 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2022-12-25T14:22:52.254+0000] {configuration.py:635} WARNING - section/key [smtp/smtp_user] not found in config
[2022-12-25T14:22:52.255+0000] {email.py:229} INFO - Email alerting: attempt 1
[2022-12-25T14:22:52.262+0000] {configuration.py:635} WARNING - section/key [smtp/smtp_user] not found in config
[2022-12-25T14:22:52.262+0000] {email.py:229} INFO - Email alerting: attempt 1
[2022-12-25T14:22:52.262+0000] {taskinstance.py:1835} ERROR - Failed to send email to: ['bala@yopmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1378, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1524, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1585, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 191, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2235, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1833, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2237, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2022-12-25T14:22:52.308+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data Traceback (most recent call last):
[2022-12-25T14:22:52.309+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data   File "/home/***/.local/bin/***", line 8, in <module>
[2022-12-25T14:22:52.309+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data     sys.exit(main())
[2022-12-25T14:22:52.310+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/__main__.py", line 39, in main
[2022-12-25T14:22:52.310+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data     args.func(args)
[2022-12-25T14:22:52.311+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 52, in command
[2022-12-25T14:22:52.311+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data     return func(*args, **kwargs)
[2022-12-25T14:22:52.312+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 108, in wrapper
[2022-12-25T14:22:52.312+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data     return f(*args, **kwargs)
[2022-12-25T14:22:52.313+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 396, in task_run
[2022-12-25T14:22:52.313+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data     _run_task_by_selected_method(args, dag, ti)
[2022-12-25T14:22:52.314+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 195, in _run_task_by_selected_method
[2022-12-25T14:22:52.314+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data     _run_raw_task(args, ti)
[2022-12-25T14:22:52.315+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 272, in _run_raw_task
[2022-12-25T14:22:52.315+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data     pool=args.pool,
[2022-12-25T14:22:52.316+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/utils/session.py", line 75, in wrapper
[2022-12-25T14:22:52.317+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data     return func(*args, session=session, **kwargs)
[2022-12-25T14:22:52.317+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1378, in _run_raw_task
[2022-12-25T14:22:52.318+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data     self._execute_task_with_callbacks(context, test_mode)
[2022-12-25T14:22:52.318+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1524, in _execute_task_with_callbacks
[2022-12-25T14:22:52.319+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data     result = self._execute_task(context, task_orig)
[2022-12-25T14:22:52.319+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1585, in _execute_task
[2022-12-25T14:22:52.320+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data     result = execute_callable(context=context)
[2022-12-25T14:22:52.320+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/operators/bash.py", line 191, in execute
[2022-12-25T14:22:52.320+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data     cwd=self.cwd,
[2022-12-25T14:22:52.321+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/hooks/subprocess.py", line 91, in run_command
[2022-12-25T14:22:52.321+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data     for raw_line in iter(self.sub_process.stdout.readline, b""):
[2022-12-25T14:22:52.321+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1485, in signal_handler
[2022-12-25T14:22:52.322+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data     raise AirflowException("Task received SIGTERM signal")
[2022-12-25T14:22:52.322+0000] {base_task_runner.py:116} INFO - Job 260: Subtask unzip_data ***.exceptions.AirflowException: Task received SIGTERM signal
[2022-12-25T14:22:52.696+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=297, status='terminated', exitcode=1, started='14:22:46') (297) terminated with exit code 1
[2022-12-25T14:22:52.697+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=308, status='terminated', started='14:22:49') (308) terminated with exit code None
